import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'

import { readFileSync } from 'fs';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const inlinePdfWorkerPlugin = {
  name: 'inline-pdf-worker',
  setup(build) {
    build.onResolve({ filter: /pdf\.worker/ }, (args) => ({
      path: require.resolve('pdfjs-dist/build/pdf.worker.mjs'),
      namespace: 'pdf-worker-inline',
    }));
    build.onLoad({ filter: /.*/, namespace: 'pdf-worker-inline' }, (args) => ({
      contents: `export default ${JSON.stringify(readFileSync(args.path, 'utf8'))};`,
      loader: 'js',
    }));
  },
};


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const args = {
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    plugins: [inlinePdfWorkerPlugin],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/closebrackets',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/comment',
        '@codemirror/fold',
        '@codemirror/gutter',
        '@codemirror/highlight',
        '@codemirror/history',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/matchbrackets',
        '@codemirror/panel',
        '@codemirror/rangeset',
        '@codemirror/rectangular-selection',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/stream-parser',
        '@codemirror/text',
        '@codemirror/tooltip',
        '@codemirror/view',
        ...builtins],
    format: 'cjs',
    target: 'es2022',
    logLevel: "info",
    sourcemap: false,
    treeShaking: true,
    outfile: 'main.js',
    
}

if (!prod) {
    args.sourcemap = 'inline';
    await (await esbuild.context(args)).watch()
} else {
    await esbuild.build(args);
}
